checkpoint:
  path: /Users/wenwen/Desktop/deepfake-whisper-features/trained_models/model__rawnet3__1708260414.446192/ckpt.pth
data:
  seed: 42
model:
  name: rawnet3
  optimizer:
    lr: 0.001
    weight_decay: 5.0e-05
  parameters: {}
